name: top_k_nn_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - pytorch=2.5.1
  - torchvision=0.16.1
  - torchaudio=2.5.1
  - jupyter=1.0.0
  - ipykernel=6.28.0
  - ipython=8.27.0
  - pip=24.2
  - pip:
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.0
platforms:
  - linux-64
  - win-64
  - osx-64


